#!/usr/bin/env sh
echo "This script runs after every commit!"
. "$(dirname -- "$0")/_/husky.sh"

if git log --format=%B -n 1 HEAD | grep -q "chore(release):"; then
  exit 0
fi
if git log --format=%B -n 1 HEAD | grep -q "docs: generate docs and update README.md"; then
  exit 0
fi
if git log --format=%B -n 1 HEAD | grep -qE "norelease|no release|dont up version"; then
  exit 0
fi

npm run release
npm run doc
git add .
git commit -m 'docs: generate docs and update README.md'
