#!/usr/bin/env sh
echo "This script runs after every commit!"
. "$(dirname -- "$0")/_/husky.sh"

if git log --format=%B -n 1 HEAD | grep -qE "chore\(release\):|docs: generate docs and update README.md|norelease|no release|dont up version"; then
  exit 0
fi


npm run release
npm run doc
git add .
git commit -m 'docs: generate docs and update README.md'
